### ISSUE TITLE
Игра не готова!

### ISSUE THREAD

**Issue by He4eT** [BiSmart/Revelation-side#1]
Привет! Молодец, что завел репозиторий.
Готовность демо-версии можно обозначить комментарием к этом Issue, а релиз - закрытием.
Успехов и идей =)

**Comment by BiSmart** [comment]
Поздно понял, что нужно оставить коммент, демка готова: https://github.com/BiSmart/Revelation-side
(на uralgamejam@gmail.com отправил вовремя)
